import Footer from "../components/footer"
import Header from "../components/header"
import '../styles/globals.css'

export const metadata = {
  title: 'Loja de Materiais',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />      
      </body>
    </html>
  )
}
